### ISSUE TITLE
Explain Heroku doesn't allow `CREATE ROLE`

### ISSUE THREAD

**Issue by benjie** [postgraphql/postgraphql.github.io#4]
https://github.com/postgraphql/postgraphql/issues/351

**Comment by pencilcheck** [comment]
Even though heroku doesn't allow create role, but it doesn't limit anything else (e.g. grants).

I have a workaround. Heroku actually allows you to create new credentials (roles) but only through their heroku API
https://devcenter.heroku.com/articles/heroku-postgresql-credentials#the-default-credential

Therefore you need to simply replace create role with heroku commands, the rest should all fall in place very quickly then you are all set.

**Comment by chadfurman** [comment]
Is it possible Heroku doesn't let you create roles with superuser or login permissions?  Could you still `create role .... with nologin nosuperuser` for example?

**Comment by pencilcheck** [comment]
No idea, I haven't tried that one, but looks like in the article indicated that you are not allowed to create any roles at all.


From the article:
```
Every newly provisioned Heroku Postgres database includes a default credential. This credential corresponds to a permissive role that is one step below the superuser. It has the ability to:


GRANT privileges to other credentials
Run SELECT on tables in the database
INSERT new data
UPDATE data
DELETE data from tables
```

**Comment by benjie** [comment]
Thanks for discovering this @pencilcheck!

From a quick read of the docs there’s no obvious way of giving noinherit; I wonder if it’s possible via “alter role foo noinherit” or if the primary user has insufficient permissions for that.

We ought to add this to the docs nonetheless

**Comment by chadfurman** [comment]
@benjie we have two docs sites now -- the graphile.github.io is the correct one to create new documentation tickets in yes?

**Comment by benjie** [comment]
Correct

**Comment by benjie** [comment]
Moved to https://github.com/graphile/graphile.github.io/issues/21
